import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import AdviceBox from '../components/advise-box/advise-box'
import adviceAPI from '../helpers/advice-api' 

const Home: NextPage = (props:any) => {
  const {response} = props
  //let advice = response.slip.advice
  
  const [advice, setAdvice] = useState(response.slip.advice)

  const randomAdvice = async ()=>{
    const res= await adviceAPI()
    setAdvice(res.slip.advice)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex justify-center items-center h-screen bg-transparent'>
        <AdviceBox advice={advice} onRandom={randomAdvice}/>
      </main>
    </div>
  )
}

export async function getServerSideProps(context:any){
  const response = await fetch('https://api.adviceslip.com/advice')
  const json = await response.json()
  const res = json
  return { 
      props: {
          response:res
      }
  }
}

export default Home
